im1 = imread("C:\Users\ms400\OneDrive\Desktop\1.jpg");
[r1, c1, ch] = size(im1);
subplot(2,2,1);
imshow(im1),title('Original im1');
im2 = imread("C:\Users\ms400\OneDrive\Desktop\2.jpg");
[r2, c2, ch] = size(im2);
subplot(2,2,2);
imshow(im2),title('Original im2');
set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
canvass = zeros(size(im1));
canvass(1:r2, 1:c2, :) = im2;
blendedRgbImage = (double(im1) + canvass) / 2;
subplot(2,2,3);
imshow(uint8(blendedRgbImage)),title('blended Rgb Image');
finalRGBImage = im1;
finalRGBImage(1:r2, 1:c2, :) = blendedRgbImage(1:r2, 1:c2, :);
finalRGBImage = uint8(finalRGBImage);
subplot(2,2,4);
imshow(finalRGBImage),title('watermark final');